---
title: "Reticulate"
author: "Peter Kowalchuk"
date: "December 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("reticulate")
```

```{r}
library(reticulate)
py_discover_config()
```

```{r}
conda_list()
use_condaenv("python2")
```

```{r}
py_config()
```


```{r}
conda_install("python2", "pandas")
```

```{r}
conda_install("python2", "scikit-learn") 
```

```{r}
conda_install("python2", "numpy") 
```

```{r}
conda_install("python2", "matplotlib") 
```

```{python}

#import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model 
from sklearn.metrics import mean_squared_error, r2_score

# Load the diabetes dataset
diabetes = datasets.load_diabetes()

# Use only one feature
diabetes_X = diabetes.data[:, np.newaxis, 2]
#print(diabetes_X)

# Split the data into training/testing sets 
diabetes_X_train = diabetes_X[:-20] 
diabetes_X_test = diabetes_X[-20:]

# Split the targets into training/testing sets 
diabetes_y_train = diabetes.target[:-20] 
diabetes_y_test = diabetes.target[-20:]

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets 
regr.fit(diabetes_X_train, diabetes_y_train)

# Make predictions using the testing set 
diabetes_y_pred = regr.predict(diabetes_X_test)

# The coefficients
print('Coefficients: \n', regr.coef_)
print('Coefficients: \n', regr.intercept_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(diabetes_y_test, diabetes_y_pred)) # Explained variance score: 1 is perfect prediction print('Variance score: %.2f' % r2_score(diabetes_y_test, diabetes_y_pred))

```

```{r}

ar<-'Peter in R'
```


```{python}
ap='Peter in py'
```

```{r}
library(reticulate)
```


```{python}
import numpy as np
X=np.array([[1],[2],[3],[4],[5]])
```

```{python}
print(X)
```



```{python}
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

X=np.array([[1],[2],[3],[4],[5]])
print(X)
y=np.array([[1],[3],[3],[4],[5]])
print(y)

regr = linear_model.LinearRegression()
regr.fit(X,y)

y_p = regr.predict(X)
print(y_p)

print('Coefficients: \n', regr.coef_)
print('Intercept: \n', regr.intercept_)
print("Mean squared error: %.2f"% mean_squared_error(y, y_p))
```


```{r}
py$X
```

